spring:
  application:
    name: promotionengine
  profiles:
    active: dev  
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url:  jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: sa
    password: null
    driver-class-name: org.h2.Driver  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        ddl-auto: create-drop   

 
server:
  port: 9092
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
firstpromo: PROMO_A
secondpromo: PROMO_B
thirdpromo: PROMO_CD
forthpromo: PROMO_ALL


